### ISSUE TITLE
Imports sem uso

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#10]
Derivado de #7. 
![image](https://user-images.githubusercontent.com/34348097/213939720-f733a506-480e-46f7-ae55-51736c56ee71.png)

**Comment by Ckk3** [comment]
Creio que ouve um engano, não alterei nenhum arquivo `print_pdfs.py` tanto que esse arquivo nem está presente na branch develop.
