### ISSUE TITLE
Repetição de código em testes

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#11]
Derivado de #7   

@Ckk3 Vejo que o bloco

```python
@pytest.fixture
def client():
    # Select your transport with ag graphql url endpoint
    transport = AIOHTTPTransport(url=GRAPHQL_MUTATION_QUERY_URL)
    # Create a GraphQL client using the defined transport
    return Client(transport=transport, fetch_schema_from_transport=True)
```

É exaustivamente repetido, me pergunto por que ele não é escrito apenas uma vez e importado onde necessita?

**Comment by filiperochalopes** [comment]
Igualmente esse:  
![image](https://user-images.githubusercontent.com/34348097/213930353-81325e28-5755-4e9f-afb7-ec5f4e7da52f.png)

**Comment by Ckk3** [comment]
Eu vi que consigo subir todas as fixtures em só uma arquivo chamado `conftest.py` e utilizar elas em todos os testes. Irei criar uma branch para aplicar essas alterações

**Comment by Ckk3** [comment]
Fiz as alterações [nessa branch](https://github.com/filiperochalopes/sistema-evolucao-medica/tree/7-refactor-generate-pdf)
