### ISSUE TITLE
Queries em txt não estão sendo sempre usadas

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#12]
Derivado de #7. 

Favor observar o padrão em `develop` instituido para os testes mais simples, possível de ver no arquivo `test_all.py`. 

Não entendi por que toda essa adição de strings e porque não estamos utilizando as requisições do txt 
![image](https://user-images.githubusercontent.com/34348097/213930522-05f4c153-f37d-4e5b-a3ec-a0cb6635de06.png)

**Comment by Ckk3** [comment]
Isso são um teste diferente, no caso, teste com somente os dados necessários. Porém, vendo agora eles não se encaixam no modelo de testes e dificulta a manutenção, vou criar arquivos .txt com esses exemplos de testes
