### ISSUE TITLE
Output falho de teste ainda em algumas ocasiões e muitos prints

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#13]
Derivado de #7. 

![image](https://user-images.githubusercontent.com/34348097/213943293-96cfa021-aef3-4f80-8857-1253d627d0b0.png)

**Comment by Ckk3** [comment]
Esse print foi um erro pontual no teste fo ficha internamento, foi o único que acabou não sendo removido antes. Já arrumei.

**Comment by Ckk3** [comment]
subi as alterações [nessa branch](https://github.com/filiperochalopes/sistema-evolucao-medica/tree/7-refactor-generate-pdf)
