### ISSUE TITLE
Campos não obrigatórios AIH SUS

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#15]
Estou tendo que lidar com obrigatoriedade de campos não obrigatórios.  
![image](https://user-images.githubusercontent.com/34348097/214455941-7f7f245f-9954-4138-8f0a-e8d127c24368.png)

**Comment by Ckk3** [comment]
Isso é decorrente do problema com o decorator current_user que eu tive

**Comment by Ckk3** [comment]
Aqui está um exemplo da função geradora da Folha de Prescrição, nela o decorator `@token_authorization` está comentado, isso se deu por eu nao conseguir implementar isso. Por isso, os dados da função não recebem somente o `current_user` com os dados de usuario e tudo mais

https://github.com/filiperochalopes/sistema-evolucao-medica/blob/a9fd627cd35f8d773430171b574b81185ef3d5b7/flaskapp/app/graphql/mutations/generate_pdfs.py#L61-L66


Assim está a função geradora do Pdf, com o `current_user` comentado, ele está pronto pra ser implementado, tanto que o código cria um dicionário  `current_user` usando os moldes do input de profissional.
https://github.com/filiperochalopes/sistema-evolucao-medica/blob/a9fd627cd35f8d773430171b574b81185ef3d5b7/flaskapp/app/services/functions/pdfs/func_generate_pdf_folha_prescricao.py#L4-L8

**Comment by Ckk3** [comment]
Peço que você tente utilizar esse decorator pois eu tive muito erros e não consegui resolver

**Comment by Ckk3** [comment]
Na verdade estão de acordo com os campos não obrigatórios descritos no figma.
![image](https://user-images.githubusercontent.com/62259205/214613022-2eae92d6-7f9f-4915-beb9-2d43a6747939.png)

Tanto que esses campos estão marcados como opcionais na função criadora:
![image](https://user-images.githubusercontent.com/62259205/214613231-02f3c670-969a-4012-82ae-efbe92f0078a.png)

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/215901545-9b69413d-8894-4038-a1f6-f7984f430714.png)

Esses campos também não são obrigatórios e estão impedindo a geração do pdf pelo método interno.

**Comment by filiperochalopes** [comment]
O termo `solicitor`não é adequado em `professional_solicitor_document`e outros. Solicitante é `request`, ficaria, por exemplo `requesting_professional_document`

**Comment by filiperochalopes** [comment]
O mesmo vale para instituição solicitante. Que seria `requesting_establishment`, melhor ainda seria `requesting_institution` lembrando que no inglês sempre o adjetivo e advérbio vem antes do substantivo.

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/216559177-81f96aa9-400f-4540-aee5-8329db44a3a0.png)

**Comment by Ckk3** [comment]
> ![image](https://user-images.githubusercontent.com/34348097/215901545-9b69413d-8894-4038-a1f6-f7984f430714.png)
> 
> Esses campos também não são obrigatórios e estão impedindo a geração do pdf pelo método interno.

Acabei de atualizar esses campos!

**Comment by Ckk3** [comment]
> 



> O termo `solicitor`não é adequado em `professional_solicitor_document`e outros. Solicitante é `request`, ficaria, por exemplo `requesting_professional_document` @Ckk3

alterei esse e outras aparições de solicitor ou solicitation no arquivo AIH SUS

**Comment by Ckk3** [comment]
> 



> O mesmo vale para instituição solicitante. Que seria `requesting_establishment`, melhor ainda seria `requesting_institution` lembrando que no inglês sempre o adjetivo e advérbio vem antes do substantivo.

Também atualizei isso

**Comment by Ckk3** [comment]
Subi as alterações na branch [#14 ](https://github.com/filiperochalopes/sistema-evolucao-medica/tree/7-refactor-generate-pdf)
