### ISSUE TITLE
Campos não obrigatórios FICHA DE INTERNAMENTO

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#16]
O campo de telefone foi adicionado dentro de PatientInput. 
![image](https://user-images.githubusercontent.com/34348097/216567639-dcef340f-c0b3-4684-a4cb-1a5f7f9b65ef.png)
não sendo necessário esse campo extra. Não entendi pq foi colocado fora se todos os itens de pacientes estavam dentro 🤔 💭

**Comment by filiperochalopes** [comment]
`current_illness_history` tem a tradução correta no termo médico como `history_of_present_illness` 
![image](https://user-images.githubusercontent.com/34348097/216568515-2ccee1ff-035f-436a-bc55-4dd0907077a2.png). 
Isso é relevante quando notamos que temos uma abreviatura muito usada e que já estava no sistema **HPI**

**Comment by Ckk3** [comment]
> O campo de telefone foi adicionado dentro de PatientInput. ![image](https://user-images.githubusercontent.com/34348097/216567639-dcef340f-c0b3-4684-a4cb-1a5f7f9b65ef.png) não sendo necessário esse campo extra. Não entendi pq foi colocado fora se todos os itens de pacientes estavam dentro 🤔 💭

Isso aconteceu porque antes não existia phone no input do Paciente, inclusive, na branch 7-refactor continua assim. Irei fazer um merge da develop nela para continuar meu desenvolvimento.
![image](https://user-images.githubusercontent.com/62259205/216864297-d59e43e0-bb33-4e22-975c-96b5aee201a7.png)

**Comment by Ckk3** [comment]
> O campo de telefone foi adicionado dentro de PatientInput. ![image](https://user-images.githubusercontent.com/34348097/216567639-dcef340f-c0b3-4684-a4cb-1a5f7f9b65ef.png) não sendo necessário esse campo extra. Não entendi pq foi colocado fora se todos os itens de pacientes estavam dentro 🤔 💭

Atualizei para o phone dentro do ficha internamento

**Comment by Ckk3** [comment]
> `current_illness_history` tem a tradução correta no termo médico como `history_of_present_illness` ![image](https://user-images.githubusercontent.com/34348097/216568515-2ccee1ff-035f-436a-bc55-4dd0907077a2.png). Isso é relevante quando notamos que temos uma abreviatura muito usada e que já estava no sistema **HPI**

Corrigido! Subi as alterações na branch https://github.com/filiperochalopes/sistema-evolucao-medica/tree/7-refactor-generate-pdf
