### ISSUE TITLE
Ajustes Pdf Relatório de Alta

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#18]
![image](https://user-images.githubusercontent.com/34348097/217430135-1c01c2e5-be3d-4f28-8c1a-f29bfd825e1f.png)

**Comment by Ckk3** [comment]
Presumo que seja a alteração para o formato ISO de data, irei fazer essa mudança em todos os documentos assim como fiz com o termo requesting. Irei finalizer essa Issue com o link para o Issue principal desse erro para fins de organização

**Comment by Ckk3** [comment]
Criei uma issue somente para alterar as datas para esse novo formato ISO -> #25
