### ISSUE TITLE
Alterações Folha de Prescrição

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#19]
![image](https://user-images.githubusercontent.com/34348097/217792793-774f4d58-9f42-4c3d-bd21-91ce5b805ca9.png)  
- [x] O padrão de string deve respeitar sempre o padrão ISO '%Y-%m-%dT%H:%M:%S'.  "dd/mm/aaa hh:mm" é um padrão de leitura humana e não de comunicação via api. 
- [x] Nessa query também temos o atributo de `print_at` que é desnecessário e deve ser excluído, pois é um `datetime` stamp que deve ser gerado automaticamente no momento da impressão.

**Comment by Ckk3** [comment]
Corrigido!
