### ISSUE TITLE
Alterações em Folha de balanço Hídrico

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#21]
1. ![image](https://user-images.githubusercontent.com/34348097/217934269-96ec14d4-40cf-4699-b0d3-9a49370ecadf.png) Devemos alterar o Input de balanço Hídrico para se adequar ao padrão do model, por isso devemos trocar `value` por `volumeMl`
2. ![image](https://user-images.githubusercontent.com/34348097/217935723-24594ddb-199c-4bd8-bfe8-4999105232cc.png) `created_at` serve para que em balanço hídrico, já que todos os registros já tem seu próprio `created_at`? Deve ser retirado se não tiver funcionalidade.

**Comment by Ckk3** [comment]
Quanto a segunda, o created at é necessário para a data que será mostrada no documento, irei fazer o mesmo que fiz no documento Folha de Evolução na issu #22 em que retirei esse dado da mutation e utilizarei o ```created_at```  do ultimo registro de balanço hidrico

**Comment by Ckk3** [comment]
Corrigido a segunda mudança

**Comment by Ckk3** [comment]
Corrigido a primeira mudança, agora o input possui volumeMl
