### ISSUE TITLE
Alterações em Folha de Evolução

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#22]
![image](https://user-images.githubusercontent.com/34348097/217943156-17b26271-0a93-4ce0-b051-7c7ce28c9614.png)  
Não faz sentido `created_at` em folhas de evolução.  São várias as datas de criação da evolução, ela deve pegar o dia da evolução mais nova e colocar como data da evolução. Não é necessário acrescentar mais dados se já as temos nos models.
![image](https://user-images.githubusercontent.com/34348097/217944420-5362ebf2-03dc-4bfc-bd12-f70ac7139c6b.png)

**Comment by Ckk3** [comment]
Corrigido, agora esse dado é recebido pela última evolução
