### ISSUE TITLE
Intervalo default errado

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#31]
![image](https://user-images.githubusercontent.com/34348097/224565831-f5dcbf1c-4b71-4de5-b57a-0fa0bc7e62fe.png)

O intervalo padrão deve ser sempre das 7h às 7h. Se estivermos após às 7h da manhã será das 7h de hoje até as 7h do dia seguinte. Se estivermos entre 00 e 7h será de 7h de ontem até 7h de hoje.

Sem falar que esses campos não tem label. O que é a primeira data e a segunda? Como vamos identificar? É necessário que tenha uma label.

**Comment by lucasnetwork** [comment]
novamente,quais são as labels?

**Comment by filiperochalopes** [comment]
> novamente,quais são as labels?

Achei que estivesse subentendido, mas pode ser: `Data e Hora inicial` e `Data e Hora Final`

Data apenas fica incompleto já que a hora é de grande relevância nesse caso:

![image](https://user-images.githubusercontent.com/34348097/226759483-6df09591-2e0c-4059-8094-7fb8392f763c.png)
