### ISSUE TITLE
Campo de data sem label

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#32]
![image](https://user-images.githubusercontent.com/34348097/224566129-e3688c3a-ac89-4951-a1b1-86712134f696.png)

É necessário colocar uma label para identificar de que se trata o campo, essa mesmo de data nem eu sei do que se trata.

**Comment by lucasnetwork** [comment]
então,qual seria a label?

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/226759616-a24c5235-6da5-4d0c-9c8c-5e0aba5c830a.png)

`Data e Hora da Alta`
