### ISSUE TITLE
React Select por dentro da caixa de diálogo

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#37]
O mesmo problema dos demais, `react-select`está dentro da caixa de diálogo, sendo assim não consigo ver os últimos itens.

![image](https://user-images.githubusercontent.com/34348097/224569978-91a3edcb-ad5b-4854-9375-93953c5e70ae.png)

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/226760653-77938966-9386-4cc5-a282-9d91758901e5.png)

Erro continua, talvez essa seja uma solução: https://stackoverflow.com/questions/55830799/how-to-change-zindex-in-react-select-drowpdown

**Comment by lucasnetwork** [comment]
funcionou perfeitamente essa solução

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/229370732-e996a722-dc17-47b3-aec3-33cfa3b25e8f.png)
