### ISSUE TITLE
Tratamento de erros

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#40]
Pelo que pude nota a forma de tratar os erros está bem diferente a depender da requisição, como se fossem funções totalmente diferentes e independentes, por exemplo aqui ao tentar atualizar as pendências.  

![image](https://user-images.githubusercontent.com/34348097/224570505-a24b5537-353f-4a2f-99b9-253ac7f340c4.png)

Existe um erro a ser escrito porém aparece essa informação genérica. É interessante que seja criada uma função que trate as exceções liberando automaticamente um toast. Algo como:

```js
function async handleRequest(request){
  response = await request
  if(response.errors){
    toast(response.errors)
  }else if(response.code !== 200){
    toast("Ocorreu um erro na requisição, favor tentar novamente ou entrar em contato com o suporte")
    enviarEmail("Texto do erro retornado HTTP")
  }else{
    return response.data
  }
  return null 
}
```

**Comment by lucasnetwork** [comment]
Criado o hook useHandleErrors pra esse fim.
