### ISSUE TITLE
Após cadastro de nova evolução, esta não aparece na tela de prontuário

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#41]
![image](https://user-images.githubusercontent.com/34348097/224571109-b4bc8626-329c-40a5-be33-b988463037f0.png)

O mesmo acontece para pendências:

![image](https://user-images.githubusercontent.com/34348097/224571173-85ca5700-a354-45f3-9f0e-2e6c5bb20654.png)
![image](https://user-images.githubusercontent.com/34348097/224571184-4679e8ed-d043-4932-8753-4cac4bca179d.png)

**Comment by lucasnetwork** [comment]
![image](https://user-images.githubusercontent.com/47489963/224792590-22f3dcf1-9727-48e4-b368-d915d3e8dfde.png)
De acordo com a minha requisição, só recebo uma

**Comment by filiperochalopes** [comment]
Estou em servidor local, para conseguir esse teste você precisa cadastrar uma evolução e testar:  

![image](https://user-images.githubusercontent.com/34348097/226757688-fc64856b-a69a-4940-8cf7-47669e96be7c.png)

![image](https://user-images.githubusercontent.com/34348097/226757753-a7678612-ea49-4594-9cdc-5938ddda9eff.png)

Acabei de testar e, com nova atualização ela apareceu, porém sem data. Todos os registros nessa página devem ser datados para melhor compreensão da história do paciente. Deve datar as evoluções e a prescrição também.

![image](https://user-images.githubusercontent.com/34348097/226757996-561b51f3-2105-45d1-9c3d-e0e2a5cb145e.png)

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/229369498-85da032e-9d6b-453e-8e0a-c21e20f85993.png)
