### ISSUE TITLE
Estado inicial de Formulário de Sinais Vitais

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#42]
![image](https://user-images.githubusercontent.com/34348097/224571248-a3c7895b-4f05-40d4-a5f5-ac76dbe666e8.png)
Esse formulário deve estar sempre vazio ao abrir, o campo de localização da dor deve ficar no modo desabilitado, assim como os botões de Impressão de Prescrição Externa e Solicitação de Exames.  

![image](https://user-images.githubusercontent.com/34348097/224571394-caa26097-d62a-4407-ad92-3978732d557a.png)

**Comment by lucasnetwork** [comment]
Achei que deveria trazer  os dados vitais mais  recentes

**Comment by filiperochalopes** [comment]
no caso esse formulário serve para adicionar novos, e geralmente são bem diferentes dos anteriores, a evolução só copia pq geralmente são bem semelhantes e muda apenas algumas coisas.  

![image](https://user-images.githubusercontent.com/34348097/226761603-c1fd5d16-b33b-437c-bfec-bf32ca5b1fd7.png)

Temos erros de campos não obrigatórios e por cima em inglês.

**Comment by filiperochalopes** [comment]
Sem campos obrigatórios. 

![image](https://user-images.githubusercontent.com/34348097/226761893-07adf368-7c71-44ec-b153-4c9b9c3feec0.png)

Os erros só devem ser mostrados se `touched`
