### ISSUE TITLE
Problema com data ao gerar relatório de alta

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#46]
Caso não seja preenchida a data ou orientações eles não devem ser enviadas.  

![image](https://user-images.githubusercontent.com/34348097/224571906-b20bbc65-bb0d-43f4-a92a-4f63b96a344e.png)

O fato de enviar ":00" está atrapalhando o processamento, pois não é nulo resultando em uma data vazia por não ser compreendida.

![image](https://user-images.githubusercontent.com/34348097/224571958-169970ce-a299-4020-ad20-581be854a6b8.png)

**Comment by lucasnetwork** [comment]
A data é obrigatória?

**Comment by filiperochalopes** [comment]
A data não é obrigatório. Corrigido.
