### ISSUE TITLE
Ao clicar em pesquisar pacientes nada é encontrado

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#48]
![image](https://user-images.githubusercontent.com/34348097/224573035-578f9f8c-8c03-4494-9955-9eb31c5cdd8d.png)
![image](https://user-images.githubusercontent.com/34348097/224573043-44fa2110-78e1-4ab0-8b92-771e03a37e37.png)

**Comment by lucasnetwork** [comment]
esta usando a rota patients e não a patient

![image](https://user-images.githubusercontent.com/47489963/224783380-10f37afc-de8d-413d-add2-87076ba90ca8.png)

na rota patient retorna isso quando eu não peço o id

![image](https://user-images.githubusercontent.com/47489963/224783479-5332de47-990f-4a0c-bb1e-d7ccabf4f16d.png)
e isso quando quando peço o id

query que passo:


 patient(id: $id, queryNameCnsCpf: $queryNameCnsCpf) {
   id
 name
 birthdate
  sex
age
  cns
 rg
  cpf
    weightKg
   comorbidities {
    id
value 
   }
   allergies {
id
 value
  }
address {
 zipCode 
 street
 number
     neighborhood
     complement
    city
      uf
  }
}
}"
variables: {queryNameCnsCpf: "Dart"}
queryNameCnsCpf: "Dart"

**Comment by filiperochalopes** [comment]
No campo de busca deve usar `patients` mesmo conforme conversado. Resolvido.
