### ISSUE TITLE
Erro de graphql.errors persiste na branch atual

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#51]
![image](https://user-images.githubusercontent.com/34348097/224573607-60531428-5d4b-494f-a7ea-a9fce4387e8b.png)

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/226762682-0f24a192-a552-4e44-9b68-a81a862274a5.png)

Persiste, conseguiu verificar do que se trata?

**Comment by lucasnetwork** [comment]
onde esse erro ocorreu?

**Comment by filiperochalopes** [comment]
Quando encontrar de novo coloco aqui. Hoje quando naveguei não encontrei.
