### ISSUE TITLE
Em visualizar prontuário não é possível verificar o balanço hídrico

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#54]
![image](https://user-images.githubusercontent.com/34348097/226726777-a33a0a79-5922-46ac-961a-ea593e07375b.png). 

No caso esse link colocado desde o FIGMA, a intenção dela é que imprima o PDF de balanço hídrico das últimas 24h:
- Se já for depois das 7h (intervalo das 7h até as 7h do dia seguinte)
- Se já for antes das 7h do dia atual (intervalo das 7h de ontem às 7h de hoje)

**Comment by filiperochalopes** [comment]
Não foi possível testar com dados adicionais porque não tem disponibilidade do campo de balanço hídrico na atualização de Sinais Vitais.

![image](https://user-images.githubusercontent.com/34348097/229367875-4722e4d3-6f6e-4086-b23f-05e7520dc878.png)

![image](https://user-images.githubusercontent.com/34348097/229367941-4e421593-617e-4ee1-a56e-827e1fe49a6f.png)

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/230043693-d694fb29-100b-41fd-9475-6f7c05994837.png)

O campo de descrição de balanço hídrico é um daqueles selects que pode não pode adicionar outro. 

![image](https://user-images.githubusercontent.com/34348097/230043966-471c3b8f-6c5a-46ce-a7d7-8fc9cfe82706.png)

**Comment by lucasnetwork** [comment]
Esse select tem opções padrões?

**Comment by filiperochalopes** [comment]
Não consigo testar em decorrência de #35

**Comment by filiperochalopes** [comment]
Ao entrar como técnico de enfermagem aparece no SELCT "Alergias" em vez de "Descrição" e estamos conseguindo cadastrar um balanço hídrico com valor, porém sem descrição.
