### ISSUE TITLE
Campos redundantes

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#60]
Não entendi pq temos o campo de Endereço e Rua. 

![image](https://user-images.githubusercontent.com/34348097/226738100-926cdd31-3da1-4e4c-aa66-83ab7efbff51.png)

**Comment by lucasnetwork** [comment]
Creio que Endereço deveria ser complemento,certo?

**Comment by filiperochalopes** [comment]
Não sei, vc está enviando `Endereço` para `complement`. Se for esse o caso, sim. Porém a ordem de campos é Rua, complemento, número, bairro, cidade, estado. CEP. Assim como escrevemos.
