### ISSUE TITLE
Campos não obrigatórios tratados como obrigatórios

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#64]
![image](https://user-images.githubusercontent.com/34348097/226750959-3c0f4329-392c-4f31-b398-3658bc975eda.png)

Campos obrigatórios são os marcados com `!`

![image](https://user-images.githubusercontent.com/34348097/226751056-f53ba3d2-02e2-4c12-aedb-9f43f57acfbe.png)

**Comment by lucasnetwork** [comment]
![image](https://user-images.githubusercontent.com/47489963/227052753-fc54f5cd-66d1-4aab-bca0-0753178e72d6.png)
quando mando apenas os campos obrigatórios,da esse erro

**Comment by filiperochalopes** [comment]
No caso está claro aí que nome é obrigatório. Só ler o texto do erro. Vou colocar a exclamação nele também no graphql docs. Mas o erro de retorno torna isso claro de entender, ele diz `null value in column name`.

**Comment by lucasnetwork** [comment]
![image](https://user-images.githubusercontent.com/47489963/227726753-7af2db93-361b-45a2-978c-2feec2f53719.png)
segundo a documentação,não é

**Comment by lucasnetwork** [comment]
![image](https://user-images.githubusercontent.com/47489963/227726832-f8c62d33-3a4f-44fe-865c-2ca6a1bbf0d7.png)
Segundo a documentação,não é

**Comment by filiperochalopes** [comment]
Eu acabei de informar que tem um erro na documentação e que vou corrigir. Estou subindo agora, porém o erro de retorno foi claro. No caso é só pedir para corrigir na docs, já estou fazendo.

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/229372420-59e145ce-fa47-4a29-9d1a-3cea4fdc2abc.png)

`phone` é obrigatório. Em falta

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/229969260-5077f5ef-46e4-4cbf-9482-abdb4203b669.png)
