### ISSUE TITLE
Falta de feedback de erro em adicionar antibiótico

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#67]
![image](https://user-images.githubusercontent.com/34348097/226760920-fd3fd48e-4402-4b3a-9b1b-fd5a0b9f3352.png)

Erro #45 permanece, criei outro pois lá estamos lidando com a parte de campos obrigatórios.

**Comment by lucasnetwork** [comment]
![image](https://user-images.githubusercontent.com/47489963/227049793-ea259960-019a-4f40-811c-757675eceaa2.png)

**Comment by filiperochalopes** [comment]
Duplicado de https://github.com/filiperochalopes/sistema-evolucao-medica/issues/45
