### ISSUE TITLE
Criação da página de evolução compacta

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#76]

**Comment by Ckk3** [comment]
A partir das 7hrs da manhã

**Comment by filiperochalopes** [comment]
Em andamento, aguardo correção dos erros (#94 #99 #100) para fecharmos essa issue.

**Comment by Ckk3** [comment]
Solicito revisão das issues #94 #99 #100 .
Já subi as correções delas.

**Comment by filiperochalopes** [comment]
Página criada por @Ckk3
