### ISSUE TITLE
Problema na geração de APAC

### ISSUE THREAD

**Issue by filiperochalopes** [filiperochalopes/sistema-evolucao-medica#80]
Não está aparecendo a data de solicitação e também os caracteres do CNS/CPF estão bem errados. 
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/34348097/4079b9ea-b643-4600-a4ab-b4c7484d9fdd)

Causas associadas também não está sendo preenchida:
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/34348097/7b9817d8-1eb3-415c-97e1-82bba75acdca)

**Comment by filiperochalopes** [comment]
```graphql
mutation printPdf_Apac($internmentId: Int!, $extra: PrintApacExtraInput!) {
  printPdf_Apac(internmentId: $internmentId, extra: $extra) {
    base64Pdf
    __typename
  }

}
```
```json
{
  "internmentId": 1,
  "extra": {
    "procedure": {
      "code": "0206010079",
      "name": "TOMOGRAFIA COMPUTADORIZADA DO CRANIO",
      "quantity": 1
    },
    "secondaryProcedures": [],
    "diagnosis": {
      "code": "I64",
      "description": "Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico"
    },
    "ssociatedCause": {
      "code": "E101",
      "description": "Diabetes mellitus insulino-dependente - com cetoacidose"
    },
    "observations": "Teste novamente"
  }
}
```

**Comment by filiperochalopes** [comment]
O problema persiste:  
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/34348097/08cb1e22-1443-4beb-8aef-4429ed32ddb2)
Commit em que estou:
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/34348097/436e7269-126b-4011-af70-32f4cb212292)
Causas associadas continua não aparecendo apesar de enviado:
```json
{
  "operationName": "printPdf_Apac",
  "variables": {
    "internmentId": 2,
    "extra": {
      "procedure": {
        "code": "0204020018",
        "name": "MIELOGRAFIA",
        "quantity": 1
      },
      "secondaryProcedures": [],
      "diagnosis": {
        "code": "A009",
        "description": "Cólera não especificada"
      },
      "secondaryDiagnosis": {
        "code": "A009",
        "description": "Cólera não especificada"
      },
      "ssociatedCause": {
        "code": "A010",
        "description": "Febre tifóide"
      },
      "observations": "Teste total"
    }
  },
  "query": "mutation printPdf_Apac($internmentId: Int!, $extra: PrintApacExtraInput!) {\n  printPdf_Apac(internmentId: $internmentId, extra: $extra) {\n    base64Pdf\n    __typename\n  }\n}"
}
```

**Comment by Ckk3** [comment]
Causas associadas não irá aparecer por você está fazendo com campo `ssociatedCause`  que não existe na mutation
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/62259205/5889b15e-2a13-4e43-a6fb-d4661ca09ba5)
Por favor, troque para essa mutation:
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/62259205/72cbd883-f0bb-46f7-bbbc-c3074ae3f89d)
Inclusive, acho que devemos alterar essa mutation para melhor leitura

**Comment by Ckk3** [comment]
> O problema persiste: ![image](https://user-images.githubusercontent.com/34348097/255334715-08cb1e22-1443-4beb-8aef-4429ed32ddb2.png) Commit em que estou: ![image](https://user-images.githubusercontent.com/34348097/255334733-436e7269-126b-4011-af70-32f4cb212292.png) Causas associadas continua não aparecendo apesar de enviado:
> 
> ```json
> {
>   "operationName": "printPdf_Apac",
>   "variables": {
>     "internmentId": 2,
>     "extra": {
>       "procedure": {
>         "code": "0204020018",
>         "name": "MIELOGRAFIA",
>         "quantity": 1
>       },
>       "secondaryProcedures": [],
>       "diagnosis": {
>         "code": "A009",
>         "description": "Cólera não especificada"
>       },
>       "secondaryDiagnosis": {
>         "code": "A009",
>         "description": "Cólera não especificada"
>       },
>       "ssociatedCause": {
>         "code": "A010",
>         "description": "Febre tifóide"
>       },
>       "observations": "Teste total"
>     }
>   },
>   "query": "mutation printPdf_Apac($internmentId: Int!, $extra: PrintApacExtraInput!) {\n  printPdf_Apac(internmentId: $internmentId, extra: $extra) {\n    base64Pdf\n    __typename\n  }\n}"
> }
> ```

A data de solicitação está sendo enviada? Não encontrei o campo `solicitationDate` na mutation que você me enviou
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/62259205/83d540a3-6157-47c0-8692-913c5f420f86)

**Comment by filiperochalopes** [comment]
Verdade, esse é um campo obrigatório. Necessário que dê erro se não tiver sido preenchido, porém não explica o erro no campo de CPF nem o erro no campo de causas associadas, quanto a esse último vou verificar se é a má digitação do termo.

**Comment by Ckk3** [comment]
Os testes de mutation estão funcionando corretamente com o cpf e com o cns. Depois irei testar no frontend
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/62259205/9bbdc7dd-f2e9-4cb9-9e58-cf3d5b952a50)

**Comment by Ckk3** [comment]
Atualização, CPF funcionou corretamente
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/62259205/d9249f14-44b6-43ff-8a93-d9f4a1b209c4)
Preciso de ajuda em como utilizar o CNS pelo frontend.
Corrigi também algumas funções que pediam tamanho mínimo quando não era preciso.

**Comment by Ckk3** [comment]
Outra coisa, por que o sistema envia um valor vazio como undefined? 
O problema que repliquei foi este:
- Campo observações está vazio, ele PODE ser vazio, porém o front sobe um erro:
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/62259205/65235b40-1643-427a-9eb8-a7f118d8ef60)
Pelo o que consegui ver, o sistema está criando como undefined
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/62259205/f240a45d-a105-413d-ab7a-f3e58fb4d569)
Acredito que seja uma issue que devemos adicionar no frontend.

**Comment by Ckk3** [comment]
Finalizei as correções. O erro do undefined não existe, o erro aconteceu pois quando o obervations está vazio a mutation envia o hpi, e no meu exemplo de teste tinha um lorem que era maior que o limite, esse erro nao tera como acontece quando nos atualizarmos todos os campos para os paragrafos.

Assim ficou o CNS corrigido, igual estava antes:
![image](https://github.com/filiperochalopes/sistema-evolucao-medica/assets/62259205/42c95530-461b-4925-a8db-97e52ca38956)
